#!/bin/zsh

export PATH=$PATH:$HOME/.local/bin:$HOME/docs/scripts:$HOME/.local/bin/blocks

# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export LESSHISTFILE=-
export TERM=xterm-256color