zsh /home/mateusjdev/home/docs/scripts/sensitivity.sh &
dwmblocks &
clipmenud &
dunst &
exec /usr/lib/kdeconnectd &
[ -e /home/mateusjdev/home/images/wallpaper.jpg ] && feh --bg-scale /home/mateusjdev/home/images/wallpaper.jpg &
exec dwm
